# Generated by Django 3.2.9 on 2021-12-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('PatientName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Gender', models.IntegerField()),
                ('AppointmentTypeId', models.IntegerField()),
                ('AppointmentDate', models.DateField()),
                ('AppointmentTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('RoleId', models.IntegerField()),
            ],
        ),
    ]
