# Generated by Django 3.2.9 on 2021-12-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalkinClinicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('PrescriptionId', models.CharField(max_length=100)),
                ('MedicineName', models.CharField(max_length=100)),
                ('MedicineDescription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('PatientName', models.CharField(max_length=100)),
                ('PatientId', models.CharField(max_length=100)),
                ('DocterName', models.CharField(max_length=200)),
                ('DocterId', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=50)),
                ('MedicineId', models.IntegerField()),
            ],
        ),
    ]
