# Generated by Django 3.2.9 on 2021-12-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalkinClinicApp', '0002_prescribedmedicine_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='AppointmentDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='AppointmentTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='AppointmentTypeId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Gender',
            field=models.IntegerField(null=True),
        ),
    ]
