# Generated by Django 3.2.9 on 2021-12-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalkinClinicApp', '0003_auto_20211214_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='PatientId',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
